# Generated by Django 5.0.4 on 2024-05-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('image', models.URLField()),
                ('release_date', models.DateTimeField()),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(unique=True, verbose_name=models.CharField())),
            ],
        ),
    ]
